const opportunities = [
  {
    id: 1,
    company: "TechNova Solutions",
    role: "AI/ML Intern",
    location: "Bengaluru",
    mode: "Hybrid",
    type: "Internship",
    salary: "₹15,000/month",
    skills: ["Python", "Machine Learning", "SQL"],
    experience: "Fresher",
    deadline: "30 Oct 2026",
  },
  {
    id: 2,
    company: "CodeCraft Technologies",
    role: "React Developer",
    location: "Remote",
    mode: "Remote",
    type: "Internship",
    salary: "₹12,000/month",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    experience: "Fresher",
    deadline: "5 Nov 2026",
  },
  {
    id: 3,
    company: "DataBridge Systems",
    role: "Python Developer",
    location: "Bengaluru",
    mode: "On-site",
    type: "Full-time",
    salary: "₹4.5–6 LPA",
    skills: ["Python", "SQL", "APIs"],
    experience: "Fresher",
    deadline: "12 Nov 2026",
  },
  {
    id: 4,
    company: "NextGen Software",
    role: "Java Developer",
    location: "Mysuru",
    mode: "Hybrid",
    type: "Internship",
    salary: "₹10,000/month",
    skills: ["Java", "OOP", "SQL"],
    experience: "Fresher",
    deadline: "20 Nov 2026",
  },
  {
    id: 5,
    company: "InnovateAI Labs",
    role: "Data Science Intern",
    location: "Bengaluru",
    mode: "Hybrid",
    type: "Internship",
    salary: "₹18,000/month",
    skills: ["Python", "Pandas", "Machine Learning"],
    experience: "Fresher",
    deadline: "25 Nov 2026",
  },
  {
    id: 6,
    company: "WebWorks India",
    role: "Frontend Developer",
    location: "Remote",
    mode: "Remote",
    type: "Full-time",
    salary: "₹5–7 LPA",
    skills: ["React", "JavaScript", "CSS"],
    experience: "0–1 Years",
    deadline: "30 Nov 2026",
  },
];